FROM debian:buster-slim
FROM python:3.8-slim-buster
WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

EXPOSE 8080

CMD [ "python" ]